apiVersion: apps/v1
kind: Deployment
metadata:
  name: shortly
spec:
  template:
    spec:
      imagePullSecrets:
        - name: ghcr-login-secret
      containers:
        - name: shortly
          image: quay.io/matt_odonnell/shortly:b459fd3
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: shortly
            - secretRef:
                name: shortly
