---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener
spec:
  template:
    spec:
      containers:
      - name: url-shortener
        image: ghcr.io/absolutod/url-shortener:67bded4
        ports:
        - containerPort: 80
