---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener
spec:
  template:
    spec:
      imagePullSecrets:
      - name: ghcr-login-secret
      containers:
      - name: url-shortener
        image: ghcr.io/absolutod/url-shortener:80d05fa
        ports:
        - containerPort: 80
