apiVersion: apps/v1
kind: Deployment
metadata:
  name: shortly
spec:
  template:
    spec:
      imagePullSecrets:
        - name: ghcr-login-secret
      containers:
        - name: shortly
          image: quay.io/matt_odonnell/shortly:1
          ports:
            - containerPort: 80
