---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shortly
  labels:
    app: shortly
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shortly
  template:
    metadata:
      labels:
        app: shortly
    spec:
      containers:
      - name: shortly
        image: quay.io/matt_odonnell/shortly:1
        ports:
        - containerPort: 8000
