---
apiVersion: v1
kind: Service
metadata:
  name: shortly
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: shortly
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
