---
apiVersion: v1
kind: Service
metadata:
  name: url-shortener
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: url-shortener
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
